// DO NOT EDIT. This file is generated by Firebase Studio.
// To regenerate this file, run the "Get Firebase Config" command.

import { initializeApp, getApps, getApp } from "firebase/app";

// Note: This is a public configuration.
const firebaseConfig = {
  apiKey: "AIzaSyAA-wTSZ6Z7DlxL-SS0XWC9jDhSyczfpoU",
  authDomain: "scriptember-hub.firebaseapp.com",
  projectId: "scriptember-hub",
  storageBucket: "scriptember-hub.firebasestorage.app",
  messagingSenderId: "509247850435",
  appId: "1:509247850435:web:78ca9598c4084c8848df76"
};

// Initialize Firebase
let app;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

export { app };
