// DO NOT EDIT. This file is generated by Firebase Studio.
// To regenerate this file, run the "Get Firebase Config" command.

import { initializeApp, getApps, getApp } from "firebase/app";

// Note: This is a public configuration.
const firebaseConfig = {
  apiKey: "your-api-key",
  authDomain: "your-project-id.firebaseapp.com",
  projectId: "your-project-id",
  storageBucket: "your-project-id.appspot.com",
  messagingSenderId: "your-sender-id",
  appId: "your-app-id"
};

// Initialize Firebase
let app;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

export { app };
